[tool.black]
line-length = 120
skip-string-normalization = 1

[tool.isort]
profile = "black"
line_length = 120
default_section = "THIRDPARTY"
known_first_party = "pybash"
known_third_party = ["ideas", "token_utils"]